package com.zhangyongyi.mydemo.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MESSAGE_ENTITY".
 */
public class MessageEntity {

    private Integer name;
    private String message;

    public MessageEntity() {
    }

    public MessageEntity(Integer name, String message) {
        this.name = name;
        this.message = message;
    }

    public Integer getName() {
        return name;
    }

    public void setName(Integer name) {
        this.name = name;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

}
