package com.zhangyongyi.mydemo.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_ENTITY".
 */
public class UserEntity {

    private Integer account;
    private Integer password;

    public UserEntity() {
    }

    public UserEntity(Integer account, Integer password) {
        this.account = account;
        this.password = password;
    }

    public Integer getAccount() {
        return account;
    }

    public void setAccount(Integer account) {
        this.account = account;
    }

    public Integer getPassword() {
        return password;
    }

    public void setPassword(Integer password) {
        this.password = password;
    }

}
